language: generic
os: windows
before_install:
- wget https://miktex.org/download/win/miktexsetup-x64.zip
- unzip miktexsetup.zip
- sudo miktexsetup_standalone --shared=yes finish
- sudo initexmf --admin --set-config-value [MPM]AutoInstall=1
script:
- pdflatex -interaction=nonstopmode -halt-on-error caleb_resume.tex
deploy:
  provider: releases
  api_key:
    secure: XBZYz8oR5Wh0Ryzj6azZ/okAyYHhRVT9kUgS85sdutz4A7WHV/q7uOIpkpoAyr/RphxlEqiZt3+mV4Ew6sRpVTL/wp/0N6Hq/MXRBg4ApO25sxGDTac4+ZgbvPXBRrXFkIy+m8A1ie+NHgV2FshSoR6hmfVFbj3ulp7m9BAtO8ViG3jddmsGfDodvsYD0nSpA3qeqRP8kXyWc8kI0YDpor7smlNI08gX8hQOWiY7rllQPv+vZX661m/xTWz+1EuwGwPAQrBzlVgZdTmIiy9ChrV1sz4cyw7tCXXN3y706aq+kDPTySQ9zxofqYxW7mFk2gNR59jrFImU+NbMXXWF/XgKDFEStzRihVnVzMGSDjVoGsGWUTUTtzoiY5SZIy6IWAA/RVtM7UcG7+hsfjC6tzvtt1ABJ67yapX/sUBrgC6iymfBP02zBNm9yCfkM+xee2+miDJ1LKrX+k7FkQ3NIVRpX9hNkF6mwf+S1IHF2AMHvKU48EDP5eMLQiqvtA/D+0NfkrH+MACdvriNP77LsVkGyX1i6usnqp7xGOtWjQZ+lbaKs+of48rOVG6VGG+xPGmp7sN34NIyrecnV7B1B8zbEwuX5GFE4X6rIiCoDCi1h2QjLy6UobQChqfIT9XosfBkY8M5lvmUyz7kQACjRXj6NxVz6iN77tK9ejMlWpk=
  file: caleb_resume.pdf
  on:
    repo: chwerth/LaTeX_Resume
    tags: true
